### ISSUE TITLE
Glusterfs Thin Arbiter 

### ISSUE THREAD

**Issue by polachz** [h8pewou/homelab#2]
Hallo.

I'm using your Lab description as basement for my setup. Everything is clear here for me, except the GlusterFs Thin Arbiter. I'm able to install Thin-Arbiter module on my "vote" node. But I'm completely confused about the thin-arbiter.vol file.

https://github.com/gluster/glusterfs/tree/devel/extras/thin-arbiter

I think that this file must fit my other volumes, but I Can't find any other piece of information how to deal with this. 

Seem's that I'm not only one, because for example this issue:

https://github.com/gluster/glusterdocs/issues/621

Notices that doc is incomplete and confusing.

For example I'm not able to verify that the Thin Arbiter is fully functional...

Do you have any progres with the Thin Arbiter please? Can you share the volume file with us, or extend the doc  about the Thin Arbiter config steps? 

Any help will be highly appreciated.

PS: I can create real arbiter node too, because it's not as much hungry for resources as real node, but Thin Arbiter completely fit my setup needs, but is hard to configure it..

**Comment by h8pewou** [comment]
Hello @polachz!

Unfortunately, I have moved to a three PVE host configuration before I could figure out a working thin arbiter setup. I gave up on this after a lot of trial and error.

I may update the documentation to make this clear.

Cheers, Adam

**Comment by polachz** [comment]
Just  for FYI: here is functional recipe for the GlusterFS  Thin Arbiter: https://polach.me/posts/howto-setup-glusterfs-thin-arbiter-at-homelab/

**Comment by h8pewou** [comment]
This is great! Thanks for sharing! I will update the guide in a moment.
